services:
  postgres:
    image: postgres:15
    container_name: rails_postgres
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feedbacks_reports_network

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: rails_clickhouse
    environment:
      CLICKHOUSE_DB: feedback_reports_api_clickhouse_development
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feedbacks_reports_network

  redis:
    image: redis:7-alpine
    container_name: rails_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feedbacks_reports_network

  web:
    build: .
    container_name: rails_app
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/feedback_reports_api_clickhouse_development
      CLICKHOUSE_URL: http://clickhouse:8123
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    stdin_open: true
    tty: true
    networks:
      - feedbacks_reports_network

volumes:
  postgres_data:
  clickhouse_data:
  redis_data:
  bundle_cache:
networks:
  feedbacks_reports_network:
    driver: bridge