default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    adapter: postgresql
    database: feedback_reports_api_development

  clickhouse:
    adapter: clickhouse
    database: feedback_reports_api_clickhouse_development
    host: localhost
    port: 8123
    username: default
    password: ""
    migrations_paths: db/migrate_clickhouse

test:
  primary:
    <<: *default
    adapter: postgresql
    database: feedback_reports_api_test
  
  clickhouse:
    adapter: clickhouse
    database: feedback_reports_api_clickhouse_test
    host: localhost
    port: 8123
    username: default
    password: ""
    migrations_paths: db/migrate_clickhouse

production:
  <<: *default
  database: feedback_reports_api_production
  username: <%= ENV["FEEDBACK_REPORTS_API_DATABASE_USERNAME"] %>
  password: <%= ENV["FEEDBACK_REPORTS_API_DATABASE_PASSWORD"] %>
