# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  primary:
    <<: *default
    adapter: postgresql
    database: feedback_reports_api_clickhouse_development
  clickhouse:
    adapter: clickhouse
    database: default
    host: clickhouse
    port: 8123
    username: default
    password: ""
    migrations_paths: db/migrate_clickhouse

test:
  primary:
    <<: *default
    adapter: postgresql
    database: feedback_reports_api_clickhouse_test
  clickhouse:
    adapter: clickhouse
    database: default
    host: clickhouse
    port: 8123
    username: default
    password: ""
    migrations_paths: db/migrate_clickhouse

production:
  primary:
    <<: *default
    database: myapp_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
  clickhouse:
    adapter: clickhouse
    database: <%= ENV['CLICKHOUSE_DATABASE'] || 'default' %>
    host: <%= ENV['CLICKHOUSE_HOST'] || 'clickhouse' %>
    port: <%= ENV['CLICKHOUSE_PORT'] || 8123 %>
    username: <%= ENV['CLICKHOUSE_USERNAME'] || 'default' %>
    password: <%= ENV['CLICKHOUSE_PASSWORD'] || '' %>
